
services:
  app:
    image: ghcr.io/paulohfs/sgl-lacina:latest
    container_name: sgl-lacina_app_prod
    env_file:
      - .env.prod
    volumes:
      - sgl-lacina_storage:/var/www/html/storage
    networks:
      - sgl-lacina_network_prod
    depends_on:
      - db
      - redis

  web:
    image: nginx:alpine
    container_name: sgl-lacina_web_prod
    ports:
      - "8080:80"
    volumes:
      - sgl-lacina_storage:/var/www/html/storage:ro
      - ./docker/prod/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sgl-lacina_network_prod
    depends_on:
      - app

  db:
    image: 'postgres:17-alpine'
    env_file:
      - .env.prod
    container_name: sgl-lacina_db_prod
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'sgl-lacina_db_prod:/var/lib/postgresql/data'
    networks:
      - sgl-lacina_network_prod
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: 'redis:7.2-alpine'
    container_name: sgl-lacina_redis_prod
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sgl-lacina_redis_prod:/data'
    networks:
      - sgl-lacina_network_prod
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  sgl-lacina_network_prod:
    driver: bridge

volumes:
  sgl-lacina_db_prod:
    driver: local
  sgl-lacina_redis_prod:
    driver: local
  sgl-lacina_storage:
    driver: local
