import { Genero } from "./types";

export const GENEROS: Array<{
  value: Genero,
  label: string
}> = [
    { value: 'MASCULINO', label: 'Masculino' },
    { value: 'FEMININO', label: 'Feminino' },
    { value: 'OUTRO', label: 'Outro' },
  ]

export const AREAS_ATUACAO = [
  'Desenvolvimento Web',
  'Desenvolvimento Mobile',
  'Inteligência Artificial',
  'Machine Learning',
  'Data Science',
  'DevOps',
  'Cibersegurança',
  'UX/UI Design',
  'Análise de Sistemas',
  'Banco de Dados',
  'Redes de Computadores',
  'Computação em Nuvem',
  'Internet das Coisas (IoT)',
  'Realidade Virtual/Aumentada',
  'Blockchain',
  'Robótica',
  'Computação Gráfica',
  'Engenharia de Software',
  'Arquitetura de Software',
  'Gestão de Projetos',
  'Business Intelligence',
  'Automação de Processos',
  'Consultoria em TI',
  'Pesquisa e Desenvolvimento',
  'Ensino e Educação',
];

export const TECNOLOGIAS = [
  // Linguagens de Programação
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C#',
  'C++',
  'C',
  'PHP',
  'Ruby',
  'Go',
  'Rust',
  'Swift',
  'Kotlin',
  'Dart',
  'R',
  'MATLAB',
  'Scala',
  'Haskell',
  'Clojure',
  'Erlang',
  
  // Frameworks e Bibliotecas Web
  'React',
  'Angular',
  'Vue.js',
  'Next.js',
  'Nuxt.js',
  'Express.js',
  'Node.js',
  'Laravel',
  'Django',
  'Flask',
  'Spring Boot',
  'ASP.NET',
  'Ruby on Rails',
  'CodeIgniter',
  'Symfony',
  'Svelte',
  'Remix',
  
  // Mobile
  'React Native',
  'Flutter',
  'Ionic',
  'Xamarin',
  'Cordova',
  'Native Android',
  'Native iOS',
  
  // Bancos de Dados
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'SQLite',
  'Oracle',
  'SQL Server',
  'Redis',
  'Elasticsearch',
  'Firebase',
  'Supabase',
  'DynamoDB',
  'CouchDB',
  'Neo4j',
  
  // Cloud e DevOps
  'AWS',
  'Google Cloud Platform',
  'Microsoft Azure',
  'Docker',
  'Kubernetes',
  'Jenkins',
  'GitLab CI/CD',
  'GitHub Actions',
  'Terraform',
  'Ansible',
  'Nginx',
  'Apache',
  
  // Ferramentas de Desenvolvimento
  'Git',
  'GitHub',
  'GitLab',
  'Bitbucket',
  'Jira',
  'Confluence',
  'VS Code',
  'IntelliJ IDEA',
  'Eclipse',
  'Postman',
  'Insomnia',
  
  // Design e Prototipagem
  'Figma',
  'Adobe XD',
  'Sketch',
  'InVision',
  'Photoshop',
  'Illustrator',
  'After Effects',
  
  // Metodologias e Práticas
  'Scrum',
  'Kanban',
  'Test-Driven Development (TDD)',
  'Behavior-Driven Development (BDD)',
  'Clean Code',
  'SOLID',
  'Design Patterns',
  'Microservices',
  'API REST',
  'GraphQL',
  
  // AI/ML
  'TensorFlow',
  'PyTorch',
  'Scikit-learn',
  'Pandas',
  'NumPy',
  'Jupyter',
  'OpenCV',
  'Keras',
  'Hugging Face',
  
  // Outras
  'Blockchain',
  'Solidity',
  'Unity',
  'Unreal Engine',
  'Blender',
  'Arduino',
  'Raspberry Pi',
  'Linux',
  'Windows',
  'macOS',
];

export const ESTADOS = [
  { sigla: 'AC', nome: 'Acre' },
  { sigla: 'AL', nome: 'Alagoas' },
  { sigla: 'AP', nome: 'Amapá' },
  { sigla: 'AM', nome: 'Amazonas' },
  { sigla: 'BA', nome: 'Bahia' },
  { sigla: 'CE', nome: 'Ceará' },
  { sigla: 'DF', nome: 'Distrito Federal' },
  { sigla: 'ES', nome: 'Espírito Santo' },
  { sigla: 'GO', nome: 'Goiás' },
  { sigla: 'MA', nome: 'Maranhão' },
  { sigla: 'MT', nome: 'Mato Grosso' },
  { sigla: 'MS', nome: 'Mato Grosso do Sul' },
  { sigla: 'MG', nome: 'Minas Gerais' },
  { sigla: 'PA', nome: 'Pará' },
  { sigla: 'PB', nome: 'Paraíba' },
  { sigla: 'PR', nome: 'Paraná' },
  { sigla: 'PE', nome: 'Pernambuco' },
  { sigla: 'PI', nome: 'Piauí' },
  { sigla: 'RJ', nome: 'Rio de Janeiro' },
  { sigla: 'RN', nome: 'Rio Grande do Norte' },
  { sigla: 'RS', nome: 'Rio Grande do Sul' },
  { sigla: 'RO', nome: 'Rondônia' },
  { sigla: 'RR', nome: 'Roraima' },
  { sigla: 'SC', nome: 'Santa Catarina' },
  { sigla: 'SP', nome: 'São Paulo' },
  { sigla: 'SE', nome: 'Sergipe' },
  { sigla: 'TO', nome: 'Tocantins' },
];